# This is a basic workflow to help you get started with Actions

name: timestamp

# Controls when the workflow will run
on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs: # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  timestamp:

    runs-on: ubuntu-latest     # The type of runner that the job will run on

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: check out the repo
        uses: actions/checkout@v2
      
      - name: add a timestamp
        run: date >> date.txt
        
      - name: commit and push
        run: |-          
          git config user.name "simeydk"
          git config user.email "13088589+simeydk@users.noreply.github.com"
          git add -A
          git commit -m "Add a timestamp" || exit 0
          git push
